"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./layout/Header";
import Footer from "./layout/Footer";
import Story from "./components/Story";
import Categories from "./layout/Categories";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { QueryClientProvider, QueryClient } from "react-query";
import { userDataContext } from "./context/userContext";
import { useState } from "react";
import firebase from "firebase/compat/app";
import { Toaster } from "@/components/ui/toaster";

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
};

firebase.initializeApp(firebaseConfig);

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  const [user, setUser] = useState(null);
  return (
    <html lang="en">
      <body className={inter.className}>
        <userDataContext.Provider value={{ user, setUser }}>
          <QueryClientProvider client={queryClient}>
            <div className="min-h-[100dvh]">
              <Header></Header>
              <div id="cart-parent">
                {children}
                <Categories></Categories>
                <Story></Story>
                <Footer></Footer>
                <Toaster></Toaster>
              </div>
            </div>
          </QueryClientProvider>
        </userDataContext.Provider>
      </body>
    </html>
  );
}
