"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./layout/Header";
import Footer from "./layout/Footer";
import Story from "./components/Story";
import Categories from "./layout/Categories";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { QueryClientProvider, QueryClient } from "react-query";
import { ReactQueryDevtools } from "react-query/devtools";
import { userDataContext } from "./context/userContext";
import { useState } from "react";
import firebase from "firebase/compat/app";
import { Toaster } from "@/components/ui/toaster";
import { Container } from "react-bootstrap";
const firebaseConfig = {
  apiKey: "AIzaSyBirBo5uwsMxsiobcpHIsrqDNYoyrPWGcM",
  authDomain: "e-commerce-74d60.firebaseapp.com",
  projectId: "e-commerce-74d60",
  storageBucket: "e-commerce-74d60.appspot.com",
  messagingSenderId: "415702834141",
  appId: "1:415702834141:web:09a520be4766b6651eb434",
  measurementId: "G-HLXPWT5DKC",
};

firebase.initializeApp(firebaseConfig);

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  const [user, setUser] = useState(null);
  return (
    <html lang="en">
      <body className={inter.className}>
        <userDataContext.Provider value={{ user, setUser }}>
          <QueryClientProvider client={queryClient}>
            <div className="min-h-[100dvh]">
              <Header></Header>
              <div id="cart-parent">
                {children}
                <Categories></Categories>
                <Story></Story>
                <Footer></Footer>
                <Toaster></Toaster>
              </div>
            </div>
          </QueryClientProvider>
        </userDataContext.Provider>
      </body>
    </html>
  );
}
